# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: system/core/fs_mgr/libsnapshot/android/snapshot/snapshot.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='system/core/fs_mgr/libsnapshot/android/snapshot/snapshot.proto',
  package='android.snapshot',
  syntax='proto3',
  serialized_options=_b('H\003'),
  serialized_pb=_b('\n>system/core/fs_mgr/libsnapshot/android/snapshot/snapshot.proto\x12\x10\x61ndroid.snapshot\"\xe2\x01\n\x0eSnapshotStatus\x12\x0c\n\x04name\x18\x01 \x01(\t\x12.\n\x05state\x18\x02 \x01(\x0e\x32\x1f.android.snapshot.SnapshotState\x12\x13\n\x0b\x64\x65vice_size\x18\x03 \x01(\x04\x12\x15\n\rsnapshot_size\x18\x04 \x01(\x04\x12\x1a\n\x12\x63ow_partition_size\x18\x05 \x01(\x04\x12\x15\n\rcow_file_size\x18\x06 \x01(\x04\x12\x19\n\x11sectors_allocated\x18\x07 \x01(\x04\x12\x18\n\x10metadata_sectors\x18\x08 \x01(\x04*H\n\rSnapshotState\x12\x08\n\x04NONE\x10\x00\x12\x0b\n\x07\x43REATED\x10\x01\x12\x0b\n\x07MERGING\x10\x02\x12\x13\n\x0fMERGE_COMPLETED\x10\x03\x42\x02H\x03\x62\x06proto3')
)

_SNAPSHOTSTATE = _descriptor.EnumDescriptor(
  name='SnapshotState',
  full_name='android.snapshot.SnapshotState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CREATED', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MERGING', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MERGE_COMPLETED', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=313,
  serialized_end=385,
)
_sym_db.RegisterEnumDescriptor(_SNAPSHOTSTATE)

SnapshotState = enum_type_wrapper.EnumTypeWrapper(_SNAPSHOTSTATE)
NONE = 0
CREATED = 1
MERGING = 2
MERGE_COMPLETED = 3



_SNAPSHOTSTATUS = _descriptor.Descriptor(
  name='SnapshotStatus',
  full_name='android.snapshot.SnapshotStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='android.snapshot.SnapshotStatus.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='android.snapshot.SnapshotStatus.state', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_size', full_name='android.snapshot.SnapshotStatus.device_size', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='snapshot_size', full_name='android.snapshot.SnapshotStatus.snapshot_size', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cow_partition_size', full_name='android.snapshot.SnapshotStatus.cow_partition_size', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cow_file_size', full_name='android.snapshot.SnapshotStatus.cow_file_size', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sectors_allocated', full_name='android.snapshot.SnapshotStatus.sectors_allocated', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metadata_sectors', full_name='android.snapshot.SnapshotStatus.metadata_sectors', index=7,
      number=8, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=311,
)

_SNAPSHOTSTATUS.fields_by_name['state'].enum_type = _SNAPSHOTSTATE
DESCRIPTOR.message_types_by_name['SnapshotStatus'] = _SNAPSHOTSTATUS
DESCRIPTOR.enum_types_by_name['SnapshotState'] = _SNAPSHOTSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SnapshotStatus = _reflection.GeneratedProtocolMessageType('SnapshotStatus', (_message.Message,), {
  'DESCRIPTOR' : _SNAPSHOTSTATUS,
  '__module__' : 'system.core.fs_mgr.libsnapshot.android.snapshot.snapshot_pb2'
  # @@protoc_insertion_point(class_scope:android.snapshot.SnapshotStatus)
  })
_sym_db.RegisterMessage(SnapshotStatus)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
